---
  - name: Install firewalld
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - firewalld

  - name: Be sure that SSH in firewalld if present
    become: yes
    firewalld:
      port: "{{ ansible_port }}/tcp"
      permanent: true
      immediate: true
      state: enabled
    ignore_errors: "yes"
    register: ssh_port_rule_ok
    notify: Firewalld started and enabled

  - name: Add it to configuration file if it failed
    become: yes
    lineinfile:
      path: /etc/firewalld/zones/public.xml
      regexp: " *{{ item }}$"
      insertafter: '</description>$'
      line: "  {{ item }}"
    with_items:
      - "<port protocol=\"tcp\" port=\"{{ ansible_port }}\"/>"
    when: ssh_port_rule_ok.failed == True
    notify: Firewalld started and enabled
  
  - name: Run role handlers now
    meta: flush_handlers