---
  - name: Install firewalld
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - firewalld
    notify: Firewalld started and enabled

  - name: Be sure that SSH in firewalld if present
    become: yes
    firewalld:
      port: "{{ ansible_port }}/tcp"
      permanent: true
      immediate: true
      state: enabled
    ignore_errors: "yes"

  