---
  - name: Install docker and dependencies if Centos 7
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - docker
        - python-pip
        - python-docker 